server:
  port: 8095
  servlet:
    encoding:
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  application: nestco
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache

  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.220.247.78:3307/final_2405_team3
    username: final_2405_team3_user
    password: 1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            scope:
              - email
              - profile
          naver:
            client-id: ""
            client-secret: ""
            scope:
              - name
              - email
              - profile_image
            authorization-grant-type:
            redirect-uri: ""
          kakao:
            client-id: ""
            client-secret: ""
            scope:
              - profile_nickname
              #              - account_email
              - profile_image
            authorization-grant-type:
            redirect-uri: ""
            client-authentication-method: ""

        provider:
          naver:
            authorization-uri: ""
            token-uri: ""
            user-info-uri: ""
            user-name-attribute: response
          kakao:
            authorization-uri: ""
            token-uri: ""
            user-info-uri: ""
            user-name-attribute: id

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
coolsms:
  apikey:
  apisecret:
  fromnumber:

file:
  upload-dir: src/main/resources/static/uploads/thumbnails/
